---
name: "Build and Zip"
description: "Builds and zips the project"
inputs:
  zip-name:
    description: "Name of the zipped file"
    required: true
runs:
  using: "composite"
  steps:
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: "npm"
    - run: npm ci
      shell: bash
    - run: npx electron-forge package
      shell: bash
    - name: Zip the build
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "zip"
        filename: "${{ inputs.zip-name }}"
        path: "./out/"
