---

    name: 'Build and Zip'
    description: 'Builds and zips the project'
    runs:
      using: "composite"
      steps:
        - name: Use Node.js 20.x
          uses: actions/setup-node@v3
          with:
            node-version: 20.x
            cache: 'npm'
        - run: npm ci
          shell: bash
        - run: npx electron-forge package
          shell: bash
        - run: sudo apt-get install tree
          shell: bash
        - run: tree
          shell: bash
        - run: echo "Testing!"
          shell: bash
    