---
    name: Build
    
    on:
      workflow_dispatch:
      push:
        branches:
        - "main"
        tags:
          - "0.*"
          - "1.*"
      pull_request:
        branches: ["main"]
    
    jobs:
      build:
        permissions:
          contents: write
        strategy:
          matrix:
            include:
              - os: "ubuntu-latest"
                os-name: "linux-x64"
                arch: "x64"
              - os: "windows-latest"
                os-name: "windows-x64"
                arch: "x64"
              - os: "macos-latest"
                os-name: "macos-universal"
                arch: "universal"
              - os: "macos-latest"
                os-name: "macos-x64"
                arch: "x64"
        runs-on: ${{ matrix.os }}

        steps:
          - uses: actions/checkout@v3
          - name: Build and Zip
            uses: ./.github/workflows/actions/build-and-zip
            with:
              zip-name: "electron-browser-open-url-${{ matrix.os-name }}-${{ github.ref_name }}.zip"
              arch: ${{ matrix.arch }}
          - name: Publish Release
            if: startsWith(github.ref, 'refs/tags/0.') || startsWith(github.ref, 'refs/tags/1.')
            uses: ncipollo/release-action@v1
            with:
              artifacts: "electron-browser-open-url-${{ matrix.os-name }}-${{ github.ref_name }}.zip"
              token: ${{ secrets.GITHUB_TOKEN }}
              tag: ${{ github.ref_name }}
              prerelease: true
              allowUpdates: true
          
    