---
name: Node.js CI

on:
  push:
    branches: ["main", "0.*", "1.*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and Zip
        uses: ./.github/workflows/actions/build-and-zip
        with:
          zip-name: "test.zip"
      - name: Publish Release
        if: startsWith(github.ref, 'refs/heads/0.') || startsWith(github.ref, 'refs/heads/1.')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "test.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allowUpdates: true
      
