---
name: Node.js CI

on:
  push:
    branches: ["main", "0.*", "1.*"]
  pull_request:
    branches: ["main"]

env:
  ZIP_NAME: "electron-browser-open-url-linux-${{ github.ref_name }}.zip"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and Zip
        uses: ./.github/workflows/actions/build-and-zip
        with:
          zip-name: ${{ env.ZIP_NAME }}
      - name: Publish Release
        if: startsWith(github.ref, 'refs/heads/0.') || startsWith(github.ref, 'refs/heads/1.')
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.ZIP_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          prerelease: true
          allowUpdates: true
      
