---
name: Node.js CI

on:
  push:
    branches: ["main", "0.*", "1.*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and Zip
        uses: ./.github/workflows/actions/build-and-zip
        with:
          zip-name: "test.zip"
      - run: sudo apt-get install tree
        shell: bash
      - run: tree
      - name: Publish Release
        if: github.ref == 'refs/heads/0.*' || github.ref == 'refs/heads/1.*'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "test.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: false
          tag: ${{ github.ref }}
      
